apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-react
  template:
    metadata:
      labels:
        app: client-react
    spec:
      containers:
        - name: client-react
          image: client-react-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: client-react
spec:
  selector:
    app: client-react
  ports:
    - port: 8080
      targetPort: 8080
      name: http
