apiVersion: v1
kind: Secret
metadata:
  name: db-password
  namespace: demo-app
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:safepassword@postgres-postgresql.postgres.svc.cluster.local:5432/postgres