apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-db
  namespace: postgres
spec:
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: true
  superuserSecret:
    name: pg-superuser-auth